const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

const root = path.resolve(__dirname, "..");
const htmlPath = path.join(root, "index.html");
const dataDir = path.join(root, "data");
const paths = {
  assembler: path.join(dataDir, "atlas-data.js"),
  reference: path.join(dataDir, "atlas-reference.js"),
  observations: path.join(dataDir, "atlas-observations.js"),
  spatial: path.join(dataDir, "atlas-spatial.js"),
  manifest: path.join(dataDir, "atlas-data.manifest.json"),
  checksums: path.join(dataDir, "atlas-data.sha256")
};

const sha256 = (value) => crypto.createHash("sha256").update(value, "utf8").digest("hex");
const banner = (title, assignment, json) => [
  "/**",
  ` * ${title}`,
  " * Generated by scripts/extract_atlas_data.cjs; do not edit manually.",
  " */",
  `${assignment}${json};`,
  ""
].join("\n");

const parseAssignment = (source, variable) => {
  const marker = `${variable}=`;
  const start = source.indexOf(marker);
  if (start < 0) throw new Error(`Could not find ${variable} in generated resource.`);
  const jsonStart = start + marker.length;
  const jsonEnd = source.lastIndexOf(";");
  if (jsonEnd < jsonStart) throw new Error(`Could not find the end of ${variable}.`);
  return JSON.parse(source.slice(jsonStart, jsonEnd));
};

const reconstructSplitData = () => {
  if (!fs.existsSync(paths.reference) || !fs.existsSync(paths.observations) || !fs.existsSync(paths.spatial)) {
    return null;
  }
  const reference = parseAssignment(fs.readFileSync(paths.reference, "utf8"), "window.AMUR_ATLAS_REFERENCE");
  const records = parseAssignment(fs.readFileSync(paths.observations, "utf8"), "window.AMUR_ATLAS_OBSERVATIONS");
  const spatial = parseAssignment(fs.readFileSync(paths.spatial, "utf8"), "window.AMUR_ATLAS_SPATIAL");
  reference.records = records;
  reference.mapBounds3857 = spatial.mapBounds3857;
  spatial.municipalityGeometries.forEach((geometry, index) => {
    reference.municipalities[index].geometry = geometry;
  });
  spatial.settlementCoordinates.forEach(([lat, lon, x3857, y3857], index) => {
    Object.assign(reference.settlements[index], { lat, lon, x3857, y3857 });
  });
  return reference;
};

const readCanonicalData = () => {
  const html = fs.readFileSync(htmlPath, "utf8");
  const embedded = html.match(/const DATA=(.*?);\s*\r?\nconst NF=/s);
  if (embedded) return JSON.parse(embedded[1]);

  if (fs.existsSync(paths.assembler)) {
    const source = fs.readFileSync(paths.assembler, "utf8");
    if (/window\.AMUR_ATLAS_DATA=\{/.test(source)) {
      const context = { window: {} };
      vm.runInNewContext(source, context, { filename: paths.assembler, timeout: 5_000 });
      if (context.window.AMUR_ATLAS_DATA) return context.window.AMUR_ATLAS_DATA;
    }
  }

  const split = reconstructSplitData();
  if (split) return split;
  throw new Error("Could not find embedded, monolithic, or split atlas data.");
};

const data = readCanonicalData();
if (!Array.isArray(data.records) || data.records.length !== 30_232) {
  throw new Error(`Unexpected record count before extraction: ${data.records?.length ?? "missing"}.`);
}

const reference = JSON.parse(JSON.stringify(data));
reference.records = null;
reference.mapBounds3857 = null;
reference.municipalities.forEach((municipality) => {
  municipality.geometry = null;
});
reference.settlements.forEach((settlement) => {
  settlement.lat = null;
  settlement.lon = null;
  settlement.x3857 = null;
  settlement.y3857 = null;
});

const spatial = {
  mapBounds3857: data.mapBounds3857,
  municipalityGeometries: data.municipalities.map((municipality) => municipality.geometry),
  settlementCoordinates: data.settlements.map(
    (settlement) => [settlement.lat, settlement.lon, settlement.x3857, settlement.y3857]
  )
};

const resourceSources = {
  "atlas-reference.js": banner(
    "Reference data and non-spatial territory attributes for Dashboard_AM.",
    "window.AMUR_ATLAS_REFERENCE=",
    JSON.stringify(reference)
  ),
  "atlas-observations.js": banner(
    "Anonymized mortality observations for Dashboard_AM.",
    "window.AMUR_ATLAS_OBSERVATIONS=",
    JSON.stringify(data.records)
  ),
  "atlas-spatial.js": banner(
    "Optional EPSG:3857 fallback geometry for Dashboard_AM.",
    "window.AMUR_ATLAS_SPATIAL=",
    JSON.stringify(spatial)
  )
};

const spatialHash = sha256(resourceSources["atlas-spatial.js"]);
resourceSources["atlas-data.js"] = `/**
 * Runtime assembler and lazy spatial-data loader for Dashboard_AM.
 * Generated by scripts/extract_atlas_data.cjs; do not edit manually.
 */
((root, documentRef) => {
  "use strict";
  const data = root.AMUR_ATLAS_REFERENCE;
  const observations = root.AMUR_ATLAS_OBSERVATIONS;
  if (!data || !Array.isArray(observations)) {
    throw new Error("Atlas core resources failed to load before atlas-data.js.");
  }
  data.records = observations;
  root.AMUR_ATLAS_DATA = data;

  const spatialUrl = "data/atlas-spatial.js?v=${spatialHash.slice(0, 12)}";
  let spatialReady = Array.isArray(data.mapBounds3857);
  let spatialPromise = null;
  let spatialError = null;

  const emit = (status, error = null) => {
    if (typeof root.dispatchEvent !== "function" || typeof root.CustomEvent !== "function") return;
    root.dispatchEvent(new root.CustomEvent("atlas:spatial-status", {
      detail: { status, error: error ? String(error.message || error) : null }
    }));
  };

  const applySpatial = (payload) => {
    if (!payload || !Array.isArray(payload.mapBounds3857) || payload.mapBounds3857.length !== 4) {
      throw new Error("Spatial package has invalid map bounds.");
    }
    if (!Array.isArray(payload.municipalityGeometries)
      || payload.municipalityGeometries.length !== data.municipalities.length) {
      throw new Error("Spatial package has an invalid municipality geometry count.");
    }
    if (!Array.isArray(payload.settlementCoordinates)
      || payload.settlementCoordinates.length !== data.settlements.length) {
      throw new Error("Spatial package has an invalid settlement coordinate count.");
    }
    data.mapBounds3857 = payload.mapBounds3857;
    payload.municipalityGeometries.forEach((geometry, index) => {
      data.municipalities[index].geometry = geometry;
    });
    payload.settlementCoordinates.forEach((coordinates, index) => {
      const [lat, lon, x3857, y3857] = coordinates;
      Object.assign(data.settlements[index], { lat, lon, x3857, y3857 });
    });
    spatialReady = true;
    spatialError = null;
    try { delete root.AMUR_ATLAS_SPATIAL; } catch (_) { root.AMUR_ATLAS_SPATIAL = null; }
    emit("ready");
    return data;
  };

  const loadSpatial = (options = {}) => {
    if (spatialReady) return Promise.resolve(data);
    if (spatialPromise && !options.retry) return spatialPromise;
    if (!documentRef) return Promise.reject(new Error("Spatial loading requires a browser document."));
    const existing = documentRef.getElementById("amur-atlas-spatial-data");
    if (existing) existing.remove();
    spatialError = null;
    emit("loading");
    spatialPromise = new Promise((resolve, reject) => {
      const script = documentRef.createElement("script");
      script.id = "amur-atlas-spatial-data";
      script.async = true;
      script.src = spatialUrl + (options.retry ? "&retry=" + Date.now() : "");
      script.addEventListener("load", () => {
        try {
          resolve(applySpatial(root.AMUR_ATLAS_SPATIAL));
        } catch (error) {
          spatialError = error;
          spatialPromise = null;
          emit("error", error);
          reject(error);
        }
      }, { once: true });
      script.addEventListener("error", () => {
        const error = new Error("Не удалось загрузить резервную геометрию карты.");
        spatialError = error;
        spatialPromise = null;
        emit("error", error);
        reject(error);
      }, { once: true });
      documentRef.head.appendChild(script);
    });
    return spatialPromise;
  };

  root.AmurAtlasDataLoader = Object.freeze({
    applySpatial,
    loadSpatial,
    retrySpatial: () => loadSpatial({ retry: true }),
    isSpatialReady: () => spatialReady,
    getStatus: () => Object.freeze({
      coreReady: true,
      spatialReady,
      spatialLoading: Boolean(spatialPromise && !spatialReady),
      spatialError: spatialError ? String(spatialError.message || spatialError) : null,
      spatialUrl
    })
  });
})(window, typeof document === "undefined" ? null : document);
`;

const resourceMeta = Object.fromEntries(Object.entries(resourceSources).map(([file, source]) => [
  file,
  {
    sha256: sha256(source),
    bytes: Buffer.byteLength(source, "utf8")
  }
]));
const manifest = {
  schemaVersion: 2,
  canonicalDataSha256: sha256(JSON.stringify(data)),
  resources: resourceMeta,
  counts: {
    records: data.records.length,
    classes: data.classes.length,
    blocks: data.blocks.length,
    codes: data.codes.length,
    municipalities: data.municipalities.length,
    settlements: data.settlements.length
  }
};

fs.mkdirSync(dataDir, { recursive: true });
for (const [file, source] of Object.entries(resourceSources)) {
  fs.writeFileSync(path.join(dataDir, file), source, "utf8");
}
fs.writeFileSync(paths.manifest, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
fs.writeFileSync(
  paths.checksums,
  `${Object.entries(resourceMeta).map(([file, meta]) => `${meta.sha256}  ${file}`).join("\n")}\n`,
  "utf8"
);

const html = fs.readFileSync(htmlPath, "utf8");
const lineEnding = html.includes("\r\n") ? "\r\n" : "\n";
const tags = ["atlas-reference.js", "atlas-observations.js", "atlas-data.js"]
  .map((file) => `<script src="data/${file}?v=${resourceMeta[file].sha256.slice(0, 12)}"></script>`)
  .join(lineEnding);
const nextHtml = html.replace(
  /<script\s+src=["']data\/(?:atlas-reference|atlas-observations|atlas-data)\.js(?:\?[^"']*)?["']><\/script>(?:\s*<script\s+src=["']data\/(?:atlas-reference|atlas-observations|atlas-data)\.js(?:\?[^"']*)?["']><\/script>)*/,
  tags
);
if (nextHtml === html && !html.includes(tags)) {
  throw new Error("Could not update the atlas resource tags in index.html.");
}
fs.writeFileSync(htmlPath, nextHtml, "utf8");

console.log(JSON.stringify({
  status: "ok",
  canonicalDataSha256: manifest.canonicalDataSha256,
  resources: resourceMeta,
  totalSplitBytes: Object.values(resourceMeta).reduce((total, item) => total + item.bytes, 0)
}, null, 2));
